import type { Metadata } from "next";
import { Montserrat, Open_Sans } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
})
const openSans = Open_Sans({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "IW Technologies - Your Enterprise Solution Partner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${openSans.className} antialiased flex flex-col min-h-screen`}>
        <Header 
          link={{
            href: "#",
            label: "Get In Touch",
            variant: "light",
          }}
        />
        <main className="grow">
          {children}
        </main>
        <Footer 
          link={{
            href: "#",
            label: "Get In Touch",
            variant: "dark",
          }}
          />
      </body>
    </html>
  );
}
